<script setup>
import { computed, onMounted, ref } from 'vue'
import { RouterLink } from 'vue-router'
import { useRoute } from 'vue-router'

import AuthLayout from '@/components/layout/AuthLayout.vue'
import { useAuthStore } from '@/stores/auth'

const route = useRoute()
const auth = useAuthStore()

const status = ref('loading')
const message = ref('Checking the verification link...')

const verificationPayload = computed(() => ({
  id: typeof route.query.id === 'string' ? route.query.id : '',
  hash: typeof route.query.hash === 'string' ? route.query.hash : '',
  expires: typeof route.query.expires === 'string' ? route.query.expires : '',
  signature: typeof route.query.signature === 'string' ? route.query.signature : '',
}))

onMounted(async () => {
  const payload = verificationPayload.value

  if (!payload.id || !payload.hash || !payload.expires || !payload.signature) {
    status.value = 'error'
    message.value = 'The verification link is incomplete or invalid.'
    return
  }

  try {
    const response = await auth.verifyEmail(payload)
    status.value = 'success'
    message.value = response.message
  } catch (error) {
    status.value = 'error'
    message.value = error.message
  }
})
</script>

<template>
  <AuthLayout
    title="Verify your email"
    description="This screen consumes the signed verification URL generated by Laravel and keeps the user inside the SPA."
  >
    <div class="form-grid">
      <p
        class="feedback"
        :class="status === 'success' ? 'feedback--success' : status === 'error' ? 'feedback--error' : ''"
      >
        {{ message }}
      </p>

      <div class="action-bar">
        <RouterLink
          class="button"
          :to="{ name: auth.isAuthenticated ? auth.homeRouteName : 'login' }"
        >
          Continue
        </RouterLink>
        <RouterLink class="button button--ghost" :to="{ name: 'landing' }">Go home</RouterLink>
      </div>
    </div>
  </AuthLayout>
</template>
